<a href="https://colab.research.google.com/github/AndresCMontejo/Manipulando_base_de_datos_con_PANDAS/blob/main/manipulando_una_base_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
#Creando la base de datos local con la biblioteca SQLAlchemy.
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text
engine = create_engine('sqlite:///:memory:')
import pandas as pd

In [28]:
#Escribiendo los datos del archivo CSV en esta base de datos local.
archivo = '/content/drive/MyDrive/ETL/PANDAS/PANDAS I O/clientes_banco.csv'
datos = pd.read_csv(archivo)
datos.to_sql('clientes', engine, index=False)

438463

In [30]:
inspector = inspect(engine)
print(inspector.get_table_names())
query = 'SELECT * FROM Clientes'
pd.read_sql(sql=text(query), con=engine.connect()) #con = conexión

['clientes']

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [32]:
#Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000.
#Actualizando un registro de base de datos.
#Cuando ejecutemos una actualización de un banco de datos, puede que funcione o no funcione.
#Para identificar que tipo de error estará sucediendo en el futuro, se hace lo siguiente
from sqlalchemy.exc import SQLAlchemyError
query = "UPDATE clientes SET Rendimiento_anual=300000 WHERE ID_Cliente=6840104"
try: #intenta ejecutar ese sql, y si no se puede, pues se activa except
  r_set = engine.connect().execute(text(query)) #primero se ejecuta el motor, y luego se muestra alguna cosa
except SQLAlchemyError as e:
  print(e) #muestra el detalle de ese error
else:
  print('#Registros actualizados: ', r_set.rowcount) #muestra el numero de registros actualizados

#Registros actualizados:  1

In [33]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,300000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [34]:
#Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene cuenta en la institución financiera.
query = "DELETE FROM clientes WHERE ID_Cliente=5008809"
try: #intenta ejecutar ese sql, y si no se puede, pues se activa except
  r_set = engine.connect().execute(text(query)) #primero se ejecuta el motor, y luego se muestra alguna cosa
except SQLAlchemyError as e:
  print(e) #muestra el detalle de ese error
else:
  print('#Numero de registros borrados: ', r_set.rowcount) #muestra el numero de registros borrados

#Numero de registros borrados:  1

In [35]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,300000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [ ]:
#Crear un nuevo registro de cliente siguiendo las especificaciones a continuación: